---
title: "Jake's Restaurant Guide"
output: 
  html_document:
    theme: journal
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(stringr)
library(dplyr)
library(ggplot2)
library(leaflet)
library(knitr)
library(ggmap)

# Load restaurant notes data
restaurants <- read_csv("restaurants.csv") %>% arrange(name)

# Add latitude and longitude data to restaurant df
#
# TODO: Add a way to cache/update the lat/long info. Right now it's small 
# problem to re-run mutate_geocode each time but eventually fix this.
restaurants <- restaurants %>%
  data.frame() %>%            # ggmap seems not to play nice with tbl_df
  mutate_geocode(address)

# Add a column for pop
map_data <- restaurants %>%
  mutate(name = str_c("<b>", name, "</b>"),
         text = str_c(name, notes, sep = "<br/>"))

```


The map below contains `r nrow(restaurants)` pins with restaurant reviews. 


```{r, echo=FALSE}

# Create restaurants map
leaflet(map_data) %>%
  addTiles() %>%  
  setView(-82.50, 28.0, zoom = 3) %>%
  addMarkers(lng = ~lon, lat = ~lat, popup = ~text)

```

```{r, echo=FALSE}

restaurants %>%
  select(name, address, phone) %>%
  mutate(name = ifelse(test = is.na(restaurants$web.address), 
                       yes  = name, 
                       no   = str_c("[", name, "](", restaurants$web.address, ")"))) %>%
 
  kable()

```

